### ISSUE TITLE
No authentication challenges found, API Error: 0, User Message: Please check your network and try again.

### ISSUE THREAD

**Issue by dustedrob** [twitter/digits-android#17] opened 2015-08-05 23:26 UTC
Sometimes i get this error whenever i try to submit a number to receive the confirmation sms, even though i have a working internet connection. This is a permanent problem with certain phones and numbers but i haven't found correlation yet. Any idea what might be causing this?

Thanks for your help!

**Comment by rallat** [comment] 2015-08-07 02:21
Can you send a email to support with the phones you are having this permanent problem?
support@fabric.io

**Comment by rallat** [comment] 2015-08-14 22:13
Are you using okhttp? if so what version?

**Comment by dustedrob** [comment] 2015-08-17 15:02
@rallat No, we're not using it.

**Comment by patoliya** [comment] 2015-08-23 15:51
Having same issue with some phones

**Comment by MrYogi** [comment] 2015-08-26 06:31
same issue here, only with certain numbers i am getting "Please check your network and try again" error . anyone figured out cause ?

**Comment by dustedrob** [comment] 2015-08-26 18:59
@MrYogi Nope, still digging through the Digits Source code to try and debug.

**Comment by dustedrob** [comment] 2015-09-07 15:42
Just a quick update on this: I discovered that by adding a 1 at the beginning of a phone number, some would magically start working right away and i would receive a confirmation SMS. However, i cannot reproduce this with all carriers and phone numbers. It would be interesting to see if any of you guys can reproduce this too.

**Comment by rallat** [comment] 2015-09-08 21:22
Hey Thanks for reporting this.
Unfortunately these is not a bug in the Android SDK and each phone number has to be treated individually since this states come from the backend.
I will go ahead and close this ticket and please fill this form with the issue information and support will follow up
https://docs.google.com/forms/d/1ZBPwlXaOmFcfoDdeG0Km9RLHMw1a0li0I0FqJ25GFFM/viewform

**Closed by rallat** 2015-09-08 21:22 UTC

**Comment by mdenissov** [comment] 2015-11-07 08:33
Scenario:

1 Device One GSM Operator KCELL (SIM number+77018079414 ): 
Input +77018079414 result Please check your network and try again

2 Device Two GSM Operator ALTEL4G (SIM number+7701255xxxx): 
Input +77018079414 result phone sent successful.

3 Device One GSM Operator KCELL (SIM number+77018079414 ): 
Input +77018079414 result phone sent successful.

why?

**Comment by guptavps** [comment] 2016-01-12 15:19
@mdenissov  Hi, were you able to get a fix for this please. My users are getting the same problem - "Check your internet connection"...I am stuck and cant do much.

**Comment by Philip-Nunoo** [comment] 2016-02-11 14:57
Still having this issue on for android devices :cry:

**Comment by efrohnhoefer** [comment] 2016-02-11 17:03
@Philip-Nunoo have you taken a look at #44? So Jelly Bean devices shipped with errors in `URLconnection` class. The easiest workaround is to include OkHttp.
