### ISSUE TITLE
Digits 2.0 Phone Number returns null

### ISSUE THREAD

**Issue by sureshvaavel** [twitter/digits-android#78] opened 2016-08-26 07:42 UTC
I am using Digits 2.0 and the success methods returns phoneNumber as " " . when I authenticate .

when I reopen the activity by closing and opening the application . the success method is called and phoneNumber is returned 

Digits.clearActiveSession();

                    digitsAuthConfig = new AuthConfig.Builder()
                            .withAuthCallBack(new AuthCallback() {
                                @Override
                                public void success(DigitsSession session, String phoneNumber) {
                                    Toast.makeText(SplashActivity.this, phoneNumber, Toast.LENGTH_SHORT).show();
                                }

                                @Override
                                public void failure(DigitsException error) {
                                    digitsException = error;
                                    Toast.makeText(SplashActivity.this, error.getMessage(), Toast.LENGTH_SHORT).show();
                                }
                            });

                    Digits.authenticate(digitsAuthConfig.build());

**Comment by hemant1109** [comment] 2016-08-26 09:42
Same issue i am facing right now.

**Comment by AnkushBhatheja** [comment] 2016-08-26 11:18
Same issue.
Please resolve it soon.

**Comment by alexsinger** [comment] 2016-08-26 13:56
Hey everyone, thanks for the reports. This is top priority for us and the team's investigating right now to figure out what's going on and to get it resolved. I'll post updates here as we know more and you can also track our status page http://status.fabric.io/

**Comment by alexsinger** [comment] 2016-08-26 15:18
Quick update -- we've identified the root cause of the issue and are working on a fix. Stay tuned for more info. Thanks for your patience while we work through this!

**Comment by alexsinger** [comment] 2016-08-26 15:44
A fix has been deployed and sign-ins are working. Thank you again for raising this up and your patience while we worked to fix it!

**Closed** 2016-08-26 15:45 UTC
Labels: bug

**Comment by AnkushBhatheja** [comment] 2016-08-26 17:22
Thanks Sir :)
Issue resolved.
